import type { Signal, Token, WatchtowerToken } from "@/lib/types";

const now = Date.now();

export const tokens: Token[] = [
  { id: "btc", symbol: "BTC", name: "Bitcoin", market_type: "perp", is_active: true },
  { id: "eth", symbol: "ETH", name: "Ethereum", market_type: "perp", is_active: true },
  { id: "sol", symbol: "SOL", name: "Solana", market_type: "perp", is_active: true },
  { id: "hype", symbol: "HYPE", name: "Hyperliquid", market_type: "perp", is_active: true },
  { id: "xrp", symbol: "XRP", name: "Ripple", market_type: "perp", is_active: true },
  { id: "fartcoin", symbol: "FARTCOIN", name: "Fartcoin", market_type: "perp", is_active: true },
];

export const watchtowerTokens: WatchtowerToken[] = [
  {
    id: "btc",
    symbol: "BTC",
    name: "Bitcoin",
    market_type: "perp",
    is_active: true,
    current_price: 84215.4,
    change_1h: 0.8,
    change_24h: 3.6,
    signal_type: "hidden_accumulation",
    signal_score: 78,
    confidence: 0.81,
    last_updated: new Date(now - 3 * 60 * 1000).toISOString(),
    why_now: "Structure stays firm while X attention still trails the move.",
    recently_changed: false,
  },
  {
    id: "eth",
    symbol: "ETH",
    name: "Ethereum",
    market_type: "perp",
    is_active: true,
    current_price: 4628.15,
    change_1h: -0.3,
    change_24h: 1.9,
    signal_type: null,
    signal_score: null,
    confidence: null,
    last_updated: new Date(now - 9 * 60 * 1000).toISOString(),
    why_now: "Market structure is stable, but no fresh edge is active yet.",
    recently_changed: true,
  },
  {
    id: "sol",
    symbol: "SOL",
    name: "Solana",
    market_type: "perp",
    is_active: true,
    current_price: 214.73,
    change_1h: -1.4,
    change_24h: -4.8,
    signal_type: "retail_trap",
    signal_score: 82,
    confidence: 0.76,
    last_updated: new Date(now - 5 * 60 * 1000).toISOString(),
    why_now: "Attention is running hotter than structure and perp chasing is building.",
    recently_changed: true,
  },
  {
    id: "hype",
    symbol: "HYPE",
    name: "Hyperliquid",
    market_type: "perp",
    is_active: true,
    current_price: 38.42,
    change_1h: 1.7,
    change_24h: 8.9,
    signal_type: "narrative_ignition",
    signal_score: 88,
    confidence: 0.84,
    last_updated: new Date(now - 2 * 60 * 1000).toISOString(),
    why_now: "Fresh attention is accelerating into confirmed structure before crowding peaks.",
    recently_changed: true,
  },
  {
    id: "xrp",
    symbol: "XRP",
    name: "Ripple",
    market_type: "perp",
    is_active: true,
    current_price: 1.18,
    change_1h: 0.2,
    change_24h: -1.1,
    signal_type: null,
    signal_score: null,
    confidence: null,
    last_updated: new Date(now - 12 * 60 * 1000).toISOString(),
    why_now: "Rotation is active, but Scoutkat is not flagging a live divergence.",
    recently_changed: false,
  },
  {
    id: "fartcoin",
    symbol: "FARTCOIN",
    name: "Fartcoin",
    market_type: "perp",
    is_active: true,
    current_price: 0.94,
    change_1h: 3.2,
    change_24h: 14.7,
    signal_type: "narrative_ignition",
    signal_score: 74,
    confidence: 0.68,
    last_updated: new Date(now - 7 * 60 * 1000).toISOString(),
    why_now: "Narrative velocity is back, but the move is already starting to crowd.",
    recently_changed: true,
  },
];

export const watchtowerWatchlistIds = ["btc", "eth", "sol", "hype"];

export const signals: Signal[] = [
  {
    id: "sig_btc_hidden_1",
    token_id: "btc",
    token_symbol: "BTC",
    triggered_at: new Date(now - 3 * 60 * 1000).toISOString(),
    signal_type: "hidden_accumulation",
    signal_score: 78,
    confidence: 0.81,
    status: "active",
    explanation: {
      why_now:
        "Structure is holding up while public attention is still behind the move and perp positioning remains relatively calm.",
      risks: ["Funding can heat up fast", "A failed breakout would weaken the read"],
      suggested_action:
        "Keep BTC on the watchlist for continuation if structure stays strong and attention begins catching up.",
      invalidation_conditions: [
        "Structure loses efficiency on the next rotation",
        "Funding z-score jumps into crowded territory",
      ],
      evidence: ["Absorption remains firm", "Attention still lags structure"],
    },
    invalidation_json: {},
  },
  {
    id: "sig_sol_trap_1",
    token_id: "sol",
    token_symbol: "SOL",
    triggered_at: new Date(now - 5 * 60 * 1000).toISOString(),
    signal_type: "retail_trap",
    signal_score: 82,
    confidence: 0.76,
    status: "active",
    explanation: {
      why_now:
        "Attention is outrunning underlying structure and perp chasing is beginning to look crowded.",
      risks: ["Squeeze conditions can persist", "Shorting too early can be expensive"],
      suggested_action:
        "Treat SOL as a caution setup and wait for structure to confirm before trusting the move.",
      invalidation_conditions: [
        "Attention cools while structure re-accelerates",
        "Crowding metrics reset without price damage",
      ],
      evidence: ["Attention is overheated", "Crowding is rising faster than structure"],
    },
    invalidation_json: {},
  },
  {
    id: "sig_hype_narrative_1",
    token_id: "hype",
    token_symbol: "HYPE",
    triggered_at: new Date(now - 2 * 60 * 1000).toISOString(),
    signal_type: "narrative_ignition",
    signal_score: 88,
    confidence: 0.84,
    status: "active",
    explanation: {
      why_now:
        "Attention expansion is arriving with structure confirmation and the perp is not yet fully crowded.",
      risks: ["Momentum could exhaust quickly", "Narrative reversals can be violent"],
      suggested_action:
        "Keep HYPE at the top of the board while confirmation remains clean and crowding stays contained.",
      invalidation_conditions: [
        "Structure stops confirming new highs",
        "Funding and OI both overheat together",
      ],
      evidence: ["Attention breadth is expanding", "Structure still has room"],
    },
    invalidation_json: {},
  },
];
